database:
  url: "jdbc:mysql://localhost:3306/mydatabase"
  username: "username"
  password: "password"
  poolSize: 10
  tableName: "files_table"

targetDirectory: "plugins/MyPlugin/files"

discord:
  channelId: "YOUR_CHANNEL_ID" # Replace with the default channel ID or leave blank